config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :toys do
    resources :transactions, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :customer, class_name: "User"
  belongs_to :toy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :toys, dependent: :destroy
  has_many :transactions, foreign_key: "customer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_age
  def check_age
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to toys_path if user_signed_in?
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
 def index
    if params.key?(:query)
      @toys = Toy.all.select{ |toy| toy.title.include?( params[:query]) }
    else
      @toys = Toy.all
    end
  end

  def show
    @toy = Toy.find(params[:id])
  end

  def new
    @toy = Toy.new
  end

  def edit
  end

  def create
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to toy_path(@toy), notice: 'Your toy was successfully created.'
    else
      render :new
    end
  end

  private

  def toy_params
    params.require(:toy).permit(:title, :description, :price, :img_url)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def new
    @transaction = Transaction.new
    @toy = Toy.find(params[:toy_id])
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @toy = Toy.find(params[:toy_id])
    @transaction.toy = @toy
    @transaction.customer = current_user
    if @transaction.save
      redirect_to toys_path, notice: "A vos toy, prêt, jouez"
    else
      render :new
    end
  end

  def destroy
    @transaction.destroy
    redirect_to root_path
  end

  def edit
  end

  def index
    @transactions = current_user.transactions.all
    @total = 0
    current_user.transactions.all.each do |t|
       @total += t.toy.price
       p @total
    end
  end



  def show
  end

  def update
    @transaction.update(transaction_params)
    redirect_to root_path
  end

  private

  def transaction_params
    params.require(:transaction).permit(:duration)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
    @toy = @transaction.toy
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def dashboard
    @transactions = current_user.transactions.all
    @total = 0
    current_user.transactions.all.each do |t|
       @total += (t.date_end - t.date_start).to_i * t.toy.price
       p @total
    end

    @toys =  Toy.order('created_at DESC').limit(100)
  end

  def profil
  end

  def update_avatar
  current_user.update(profil_params)
  redirect_to profil_path
  end

  private
  def profil_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

  <script src="https://kit.fontawesome.com/fb1ba64fb7.js" crossorigin="anonymous"></script>
    <title>LaBonneToy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>




    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' unless controller_name == "pages" && action_name == "home"%>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" unless controller_name == "pages" && action_name == "home"%>

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
    AOS.init();
    </script>
  </body>
</html>

app/views/layouts/footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/pages/home.html.erb
<div class="video-frame">
  <%= video_tag "video.mp4", autoplay: true, loop: true, muted: true, type: "video/mp4", class: "video" %>
</div>
<!-- Modal -->
<div class="modal rounded-circle" id="legal_age" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog rounded-circle" role="document">
    <div class="modal-content d-flex justify-content-center align-items-center p-5 rounded-lg bg-light", style="opacity: 0.6">
      <h5 class="p-3"> Bienvenue sur </h5>
       <%= image_tag "la_bonne_toy.svg", class: "logo_homepage" %>
      <div class="modal-body d-flex justify-content-center">
        Avez-vous l'age de jouer ?
      </div>
      <div class="modal-footer d-flex justify-content-around">
        <%= link_to "Oui, je suis joueur 😈", toys_path, class: "btn btn-secondary" %>
        <%= link_to "Non, je n'aime pas jouer ! 🤓", "https://www.joueclub.fr/", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_toy.html.erb
<div class="card-toy" data-aos="fade-up-right">
  <%= link_to toy_path(toy) do %>
    <div class="card_toy_link">
      <div class="card-picture">
        <%= image_tag toy.img_url, alt: "alttext" %>
      </div>
      <div class="card-title">
        <%= toy.title %>
      </div>
      <div class="price">
        <%= "#{toy.price} € / le week-end" %>
      </div>
      <div class="description">
        <%= toy.description %>
      </div>
    </div>
  <% end %>
  <%= link_to toy_path(toy) do %>
    <button class="btn-gradient">Jouez avec moi</button>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to toys_path, class: "navbar-brand" do %>
    <%= image_tag "la_bonne_toy.svg", class: "logo_homepage" %>
    <% end %>
<!--
    <div class="search-caja">
    <input type="text" name="" class="search-txt" placeholder="search..."/>
    <a class="search-btn">
      <i class="fas fa-search"></i>
    </a>
    </div> -->

    <!-- <div class="search-caja"> -->
      <%= form_tag toys_path, method: :get, class: "search" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "searchTerm",
          placeholder: "Chercher un jouet"

        %>

         <button type="submit" class="searchButton">
        <i class="fa fa-search"></i>
     </button>
      <% end %>
    <!-- </div> -->

    <div class="lien_ajouter_annonce">
      <%= link_to "Ajouter une annonce", new_toy_path %>
    </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Je bavarde par message", "#", class: "dropdown-item" %>
            <%= link_to "Je consulte mes dernières folies", "#", class: "dropdown-item" %>
            <%= link_to "Je me retire", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
         <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/transactions.html.erb
<!-- <div class="gauche">

    <div class="transactions">
      <h1>Mes réservations</h1>
      <% if current_user.transactions.count == 0 %>
        <h3><%= current_user.first_name %>, vous n'avez pas encore effectué de réservations</h3>
      <% else %>
        <h3><%= current_user.first_name %>, vous avez effectué de <%= current_user.transactions.count %> réservations</h3>

        <% @transactions.each do |t| %>

          <%= link_to transaction_path(t) do %>

              <div class="transaction" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path t.toy.photos.first.key, width: 500, height: 300, crop: :fill, gravity: :face %>)">
                  <div class="card-trip-infos">

                      <h2><%= t.toy.title.upcase %> <i>(<%= t.toy.artist%>)</i></h2>
                      <% if (t.date_end - t.date_start).to_i > 1 %>
                        <p>Durée de la location: <%= (t.date_end - t.date_start).to_i %> jours</p>
                      <% else %>
                        <p>Durée de la location: <%= (t.date_end - t.date_start).to_i %> jour</p>
                      <% end %>
                      <p>Type de sextoy: <%= t.toy.category%></p>


                    <%= profile_image(t.toy.owner, class: "card-trip-user avatar-bordered",width: 40, height: 40, crop: :fill , gravity: :face) %>
                        <div class="card-trip-pricing">
                          <%= link_to edit_transaction_path(t), id: "edit" do %>
                           <i class="far fa-edit"></i>
                           <% end %>

                          <%= link_to transaction_path(t),
                            id: "delete",
                            method: :delete,
                            data: { confirm: "Voulez-vous annuler la réservation de :#{t.toy.name}?" } do %>
                            <i class="fas fa-trash"></i>
                            <% end %>

                          <h2>  <%= (t.date_end - t.date_start).to_i * t.toy.price %> €</h2>
                        </div>
                  </div>
              </div>
          <% end %>
        <% end %>
    </div>

    <div class="droite">
      <h3>Total de vos réservations</h3>

        <% @transactions.each_with_index do |t,i| %>
          <p>Réservation <%= i+1 %> : <%= (t.date_end - t.date_start).to_i * t.toy.price%> €</p>
        <% end %>

      <p id="ht">Montant total : <%= @total.round(2) %> €</p>
    </div>

      <% end %>
</div>
 -->

app/views/toys/index.html.erb
<div class="content-container">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://assets.afcdn.com/story/20180620/1163976_w980h638c1cx776cy701.jpg)">
  </div>
  <div class="container-banner">
  </div>

  <div class="container-cards">
    <% @toys.each do |element| %>
      <%= render "shared/card_toy", toy: element %>
    <% end %>
  </div>
</div>

app/views/toys/new.html.erb
<%= simple_form_for(@toy) do |f| %>
  <%= f.input :title, label: "Titre" %>
  <%= f.input :description %>
  <%= f.input :price, label: "Prix à la journée" %>
  <%= f.input :img_url, label: "Image" %>
  <%= f.submit class: "btn-gradient" %>
<% end %>

app/views/toys/show.html.erb
<div class="container_cards_show">
  <div class="bloc_cards_show">
    <div class="card-title_show">
      <%= @toy.title %>
    </div>
    <div class="card-picture_show">
      <%= image_tag @toy.img_url, alt: "alttext" %>
    </div>
    <div class="description_show">
      <%= @toy.description %>
    </div>
    <div>
      <%= "#{@toy.price} € / le week-end" %>
    </div>
    <%= link_to "Reservez-moi", new_toy_transaction_path(@toy), class: "btn-gradient" %>
  </div>
</div>

app/views/transactions/_form.html.erb
<div class="form-container">
  <%= simple_form_for([@toy, @transaction]) do |f| %>
    <%= f.input :duration %>
    <%= f.submit "Réserver", class: "btn btn-gradient" %>
  <% end %>
</div>

app/views/transactions/index.html.erb
<div class="container">
  <%= render 'shared/transactions' %>
</div>

app/views/transactions/new.html.erb
<h2>toy : <%= @toy.title %></h2>
  <%= render "form", transaction: @transaction, toy: @toy %>
<br>
<%= link_to "retour", toy_path(@toy), class: "btn btn-ghost" %>

app/views/transactions/show.html.erb
 <h1><%= @transaction.toy.name %></h1>
  <h2><%= @transaction.toy.user %></h2>

<%= render 'shared/carousel', toy: @transaction.toy %>

<div class="container-text my-4">
  <div class="container-infos">
  <p><%= "début de location : #{@transaction.date_start}" %></p>
  <p><%= "fin de location : #{@transaction.date_end}" %></p>
  <p><%= "montant de la location : #{@montant} €" %></p>

</div>

<div class= "d-inline-flex">
<%= button_to "retour aux réservations", transactions_path, method: :get, class: "btn btn-ghost" %>

<%= button_to 'modifier', edit_transaction_path(@transaction), method: :get,class: "btn btn-ghost"%>

<%= button_to 'annuler la réservation', transaction_path(@transaction),
        method: :delete,
        data: { confirm: "Voulez-vous annuler la réservation de :#{@transaction.toy.name}?" },
        class: "btn btn-ghost" %>
</div>